### ISSUE TITLE
Friendly Fire

### ISSUE THREAD

**Issue by mineo333** [mineo333/Video-Game-Design-Frost-2017#7]
How should we deal with friendly fire?
-From the coding perceptive
Here are solutions:
Should we remove the rigid body temporarily then reinstate it
     -Problem: It will be hard and inefficient to add and remove the rigidbody
Any other solutions?

**Comment by AkashJ7** [comment]
Friendly fire with who? Isn't this just the main serf versus the king and his minions? It is not like he will have animated friends, which will be too much work and take too much time.
If the friendly fire is for the minions, then it is not a problem. Just make the "hit sensor" activate if the rigidbody is "on player" or has the player tag

**Comment by 2NEON11** [comment]
The friendly fire is for the other serfs, who are helping him. I'm assuming there is a big fight scene with all the serfs and all the minions/guards. One way we can stop friendly fire is to set tags like "enemy" and "friendly serf" and "king" and stuff like that, and then we can set an if statement like

`if (player.tag === "friendly serf") {
           GetComponent.<Health>().Health = 0--
} else if (player.tag === "enemy") {
           GetComponent.<Health>().Health = 1--
}`

I looked at the script for shot and damage in the "Heart" script, and I noticed that you already did something like this.

`if (shot.isEnemyShot != isEnemy)
            {
                Damage(shot.damage);
}`

Is this not working? Because my idea is pretty similar and that would make my idea useless

**Comment by mineo333** [comment]
Friendly Fire between enemies

**Comment by AkashJ7** [comment]
If it is between the enemies, then my idea should be fine.

Or, if it is necessary, we can create two different gameObjects for the serf's magic and the minions' magic, and have both of them react to different sensors. One on the serf, and the unique serf's magic, on the minions. I don't know if this is the most efficient way, but I think that this one will work better and give better results than other methods.

**Comment by mineo333** [comment]
Okay thanks for your feedback will patch when I get time

**Comment by mineo333** [comment]
Actually I will take John's idea just because it will be easer to code

**Comment by mineo333** [comment]
Thanks John for the code
