### ISSUE TITLE
Minions

### ISSUE THREAD

**Issue by mineo333** [mineo333/Video-Game-Design-Frost-2017#9]
On the other issue you said:
__________________________________________________________________________________________________________________
Friendly fire with who? Isn't this just the main serf versus the king and his minions? It is not like he will have animated friends, which will be too much work and take too much time.
If the friendly fire is for the minions, then it is not a problem. Just make the "hit sensor" activate if the rigidbody is "on player" or has the player tag
__________________________________________________________________________________________________________________
However we will have minions

**Comment by 2NEON11** [comment]
We will also have friendly serfs which join our main serf through his rebellion.

Is this issue about what minions should look like or how we should program their friendly fire?

Here is the link to a minion I made (btw, weren't the guards going to be our minions?)
[(http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/#?sex=male&body=darkelf&eyes=yellow&ears=elven&nose=big&clothes=none&hair=none&spikes=none&gloves=metal&hat=hood_cloth&shoes=none&weapon=wand_wood&legs=pants_white )
]
I put these in Dropbox as Minion.

The friendly fire was fixed by John.

**Comment by 2NEON11** [comment]
Here is a Minion Beta
[http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/#?sex=male&body=darkelf&eyes=red&ears=elven&nose=big&clothes=none&hair=none&spikes=none&gloves=metal&hat=bandana_red&shoes=none&weapon=wand_wood&legs=pants_white]((http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/#?sex=male&body=darkelf&eyes=red&ears=elven&nose=big&clothes=none&hair=none&spikes=none&gloves=metal&hat=bandana_red&shoes=none&weapon=wand_wood&legs=pants_white))
